# See https://www.chirpstack.io/gateway-bridge/install/config/ for a full
# configuration example and documentation.
[general]
# debug=5, info=4, warning=3, error=2, fatal=1, panic=0
log_level=4

[integration.mqtt.auth.generic]
servers=["tcp://mosquitto:1883"]
username=""
password=""


# for simpler protocol
[integration]
marshaler="json"

